
import { Student, Badge, SkillCategory } from './types';
import { Layout, Users, Book, Trophy, Target } from 'lucide-react';

export const SKILL_CATEGORIES: SkillCategory[] = [
  'Development', 'AI & Data', 'Design', 'Academics', 'Soft Skills'
];

// Map individual skills to categories for robust filtering
export const SKILL_MAP: Record<string, SkillCategory> = {
  'React': 'Development',
  'Node.js': 'Development',
  'Tailwind': 'Development',
  'TypeScript': 'Development',
  'HTML': 'Development',
  'CSS': 'Development',
  'Java': 'Development',
  'C++': 'Development',
  'Python': 'AI & Data',
  'Machine Learning': 'AI & Data',
  'PyTorch': 'AI & Data',
  'SQL': 'AI & Data',
  'Data Structures': 'Academics',
  'System Design': 'Development',
  'Figma': 'Design',
  'UI Design': 'Design',
  'Interaction Design': 'Design',
  'Public Speaking': 'Soft Skills',
  'Technical Writing': 'Soft Skills',
  'Communication': 'Soft Skills',
  'Programming': 'Development'
};

export const BADGES: Badge[] = [
  { id: 'b1', name: 'Eagle Eye', icon: '🦅', description: 'Spotting 10 errors in sessions' },
  { id: 'b2', name: 'Master Tutor', icon: '🏆', description: 'Taught over 50 hours' },
  { id: 'b3', name: 'Knowledge Sponge', icon: '🧽', description: 'Learned 5 new skills' },
  { id: 'b4', name: 'Streak King', icon: '🔥', description: '7-day learning streak' },
];

export const MOCK_STUDENTS: Student[] = [
  {
    id: 's1',
    name: 'Atharv balsih',
    college: 'Engineering Institute',
    branch: 'Computer Science',
    year: 3,
    strongSkills: ['React', 'Node.js', 'Tailwind'],
    weakSkills: ['Data Structures', 'C++', 'System Design'],
    teachingScore: 4.8,
    learningScore: 4.5,
    skillReputation: 4,
    points: 1250,
    rank: 'Pro',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Atharv',
    badges: [BADGES[0], BADGES[1]],
    streak: 5,
  },
  {
    id: 's2',
    name: 'Om Noobda',
    college: 'Tech University',
    branch: 'Information Technology',
    year: 2,
    strongSkills: ['Data Structures', 'C++', 'Java'],
    weakSkills: ['React', 'CSS', 'Figma'],
    teachingScore: 4.9,
    learningScore: 4.7,
    skillReputation: 5,
    points: 1400,
    rank: 'Expert',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Om',
    badges: [BADGES[2], BADGES[3]],
    streak: 12,
  },
  {
    id: 's3',
    name: 'Shubham Gandu',
    college: 'State Tech',
    branch: 'Software Engineering',
    year: 4,
    strongSkills: ['System Design', 'Python', 'Machine Learning'],
    weakSkills: ['Node.js', 'TypeScript'],
    teachingScore: 4.6,
    learningScore: 4.8,
    skillReputation: 3,
    points: 900,
    rank: 'Apprentice',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Shubham',
    badges: [BADGES[1]],
    streak: 3,
  },
  {
    id: 's4',
    name: 'Yashraj Bhaira',
    college: 'Design School',
    branch: 'Interaction Design',
    year: 1,
    strongSkills: ['Figma', 'UI Design', 'HTML'],
    weakSkills: ['Python', 'SQL', 'React'],
    teachingScore: 4.2,
    learningScore: 4.9,
    skillReputation: 4,
    points: 500,
    rank: 'Novice',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yashraj',
    badges: [],
    streak: 1,
  },
  {
    id: 's5',
    name: 'Varad Kamchor',
    college: 'Tech University',
    branch: 'AI Engineering',
    year: 3,
    strongSkills: ['Python', 'PyTorch', 'SQL'],
    weakSkills: ['Figma', 'CSS'],
    teachingScore: 4.7,
    learningScore: 4.3,
    skillReputation: 4,
    points: 1100,
    rank: 'Expert',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Varad',
    badges: [BADGES[1], BADGES[3]],
    streak: 8,
  },
  {
    id: 's6',
    name: 'Yashwardhan Tingu',
    college: 'Liberal Arts College',
    branch: 'Communication',
    year: 2,
    strongSkills: ['Public Speaking', 'Technical Writing'],
    weakSkills: ['Java', 'C++'],
    teachingScore: 4.5,
    learningScore: 4.2,
    skillReputation: 3,
    points: 750,
    rank: 'Apprentice',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Yashwardhan',
    badges: [BADGES[0]],
    streak: 4,
  }
];

export const NAV_ITEMS = [
  { id: 'dashboard', label: 'Dashboard', icon: Layout },
  { id: 'matching', label: 'Explore Hub', icon: Users },
  { id: 'sessions', label: 'History', icon: Book },
  { id: 'leaderboard', label: 'Rankings', icon: Trophy },
  { id: 'marketplace', label: 'Assets', icon: Target },
];
